USE customer_behavior;
SELECT * FROM mytable;

-- Q1. What is the total revenue generated by male vs female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM mytable
GROUP BY gender;

-- Q2. Which customers used a discount but still spent more than the average purchase amount?
SELECT customer_id, purchase_amount
FROM mytable
WHERE discount_applied = 'Yes' AND purchase_amount >= (SELECT AVG(purchase_amount) FROM mytable);

-- Q3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) AS "avg_review"
FROM mytable
GROUP BY item_purchased
ORDER BY AVG(review_rating) DESC
LIMIT 5;

-- Q4. Compare the average Purchase Amounts betwen Standard and Express Shipping.
SELECT shipping_type, ROUND(AVG(purchase_amount), 2) AS "avg_purchase_amount"
FROM mytable
WHERE shipping_type = "Standard" or shipping_type = "Express"
GROUP BY shipping_type;

-- Q5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, ROUND(AVG(purchase_amount), 2) AS "avg_spend", ROUND(SUM(purchase_amount), 2) as"total_revenue"
FROM mytable
GROUP BY subscription_status;

-- Q6. Which 5 products had the highest percentage of purchases with discounts applied?
SELECT item_purchased, ROUND(SUM(CASE WHEN discount_applied = 'Yes' THEN 1 ELSE 0 END)/COUNT(*) * 100, 2) as discount_rate
FROM mytable
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;

-- Q7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, 
-- and show the count of each segment.
WITH customer_type as (
SELECT customer_id, previous_purchases,
CASE 
	WHEN previous_purchases = 1 THEN 'New'
    WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
    ELSE 'Loyal'
    END AS customer_segment
FROM mytable
)

SELECT customer_segment, count(*) AS "num_of_customers"
FROM customer_type
GROUP BY customer_segment;

-- Q8. What are the top 3 most purchased products in each category?
WITH item_counts AS (
SELECT category, item_purchased, COUNT(customer_id) AS total_orders,
ROW_NUMBER() OVER(PARTITION BY category ORDER BY COUNT(customer_id) DESC) AS item_rank
FROM customer
GROUP BY category, item_purchased)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts
WHERE item_rank <= 3;

-- Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM mytable
WHERE previous_purchases > 5
GROUP BY subscription_status;

-- Q10. WHat is the revenue contribution of each age group?
SELECT age_group, SUM(purchase_amount) AS total_revenue
FROM mytable
GROUP BY age_group
ORDER BY total_revenue DESC;
